### ISSUE TITLE
IOS : ld: framework not found IJKMediaFramework

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [ljunb/ijkplayer-rn-playground#4]

**Comment by ljunb** [comment]
参考 [如何快速的开发一个完整的iOS直播app(播放篇)](https://www.jianshu.com/p/7b2f1df74420)，framework太大，150+m，被我忽略掉的

另建议可关注 [这个仓库](https://github.com/syanbo/react-native-aliyun-player)，也可一起参与开发完善

**Comment by NrqhEIcsRi004** [comment]
错误解决了。。。

**Comment by MartingKing** [comment]
我也遇到这个错误了，怎么解决的
