### ISSUE TITLE
请问这个库现在支持双平台的么？

### ISSUE THREAD

**Issue by Yunnathai** [ljunb/ijkplayer-rn-playground#5]
请问这个库现在支持双平台的么？
最近有需求要做一个视频播放功能，看了你的功能介绍，挺齐全，想问下现在基本功能都可以么？

**Comment by ljunb** [comment]
@jamninetyfive 之前只是在iOS下运行通过的，Android端没有继续写，而且也只是自己尝试性的练习，不具备用到生产的条件的

**Comment by Yunnathai** [comment]
谢谢回复 。
